server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.kangxu.device.pojo

#打印sql语句
logging:
  level:
    com.kangxu.device.mapper : debug

spring:
  application:
    name: device-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://120.55.46.101:3333/kangxu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wuyanwen12#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/



